// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

public class Options
{
	public static float DAMP = 0.90f;

}

public class PlayerState
{
	public static PlayerSprite player;

	public static bool SWIM_LEFT = false;
	public static bool SWIM_RIGHT = false;

	public static int MAX_SPEED = 5;
	public static float ACCEL = 0.5f;

	public static int SCORE = 0;
	public static float DEPTH = 0;

	public static float DEATH_TIME = 0.0f;
}

public class Level
{
	public static bool STARTED = true;
	public static List<EnemySprite> enemyList;
}

public class Inventory
{
	public static char Items;
}

